### ISSUE TITLE
Compatibility with new release of AMS.

### ISSUE THREAD

**Issue by alcabcucu** [usineur/rawgl#1]
Sorry to ask, but as you fixed your port of Fade to Black, could you also fix these two ports (Another World and specially Heart of the Alien) to be compatible with the new AMS 0.19.0 and firmware 12.0.0.

Thanks a lot!!!

**Comment by usineur** [comment]
Done
https://gbatemp.net/threads/another-world-and-heart-of-the-alien-for-switch.505416/page-3#post-9481663
